[package]
name = "lol_coin"
version = "0.1.0"
edition = "2021"
description = "LOL-Coin Staking Program"

[lib]
crate-type = ["cdylib", "lib"]
name = "lol_coin"

[dependencies]
anchor-lang = "0.30.1"
anchor-spl = "0.30.1"
solana-program = "1.16.1"

